baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Enrico Kaack'
theme = 'hello-friend-ng'
paginate = 10

[params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"

# Subtitle for home
homeSubtitle = "Software Developer // Sport Addict //  Aviation and Space Enthusisast"

archetypeDir = "archetypes"
contentDir = "content"
dataDir = "data"
layoutDir = "layouts"
publishDir = "public"

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false

# Enable sharing buttons, if you like
enableSharingButtons = false

# Show a global language switcher in the navigation bar
enableGlobalLanguageMenu = false

# Metadata mostly used in document's head
description = "Personal Blog and Project Portfolio of Enrico Kaack "
keywords = "homepage, blog, portfolio"
images = [""]

[params.footer]
trademark = 2023
rss = true
copyright = true
author = true

topText = ['<a href="/impressum">Impressum</a>']
bottomText = [
    "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
    'Theme made with &#10084; by <a href="https://github.com/rhazdon\">Djordje Atlialp</a> under <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>',
]
[params.logo]
logoMark = ">"
logoText = "/home/"
logoHomeLink = "/"
# Set true to remove the logo cursor entirely.
# logoCursorDisabled = false
# Set to a valid CSS color to change the cursor in the logo.
# logoCursorColor    = "#67a2c9"
# Set to a valid CSS time value to change the animation duration, "0s" to disable.
# logoCursorAnimate  = "2s"
# Append the current url pathname to logoText 
# logoCursorPathname = true

# Uncomment this if you want a portrait on your start page
#
# [params.portrait]
#   path     = "/img/image.jpg"
#   alt      = "Portrait"
#   maxWidth = "50px"


[[params.social]]
name = "github"
url = "https://github.com/enrico-kaack"
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/enrico-kaack"


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "posts/"
[[menu.main]]
identifier = "aboutme"
name = "About Me"
url = "/about"
[[menu.main]]
identifier = "projects"
name = "Projects"
url = "projects/"
